production:
  environment: production
  production_environment: true

staging:
  auto_deploy_on: refs/heads/release
  environment: staging
  production_environment: false

development:
  auto_deploy_on: refs/heads/master
  environment: development
  production_environment: false
  
review:
  environment: pr-${{ pr }}
  transient_environment: true
  production_environment: false
