---
environment: development

deployment:
  replicaCount: 1
  env:
    token_list: /data/tokens-eth.json
    token_image_dir: /data/tokens
  resources: 
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 50m
      memory: 100Mi

service:
  port: 8000

ingress:
  host: tokeninfo-dev.endpass.com