apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tokeninfo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tokeninfo.name" . }}
    environment: {{ .Values.environment }}
    chart: {{ template "tokeninfo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "tokeninfo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "tokeninfo.name" . }}
        environment: {{ .Values.environment }}
        chart: {{ template "tokeninfo.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ template "tokeninfo.name" . }}
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: tokeninfo
                  key: env
            - name: TOKEN_LIST
              valueFrom:
                configMapKeyRef:
                  name: tokeninfo
                  key: token_list
            - name: TOKEN_IMAGE_DIR
              valueFrom:
                configMapKeyRef:
                  name: tokeninfo
                  key: token_image_dir
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true