apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tokeninfo
    env: dev
  name: tokeninfo
  namespace: {{ template "tokeninfo.namespace" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tokeninfo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tokeninfo
        env: dev
    spec:
      containers:
        - name: tokeninfo
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: tokeninfo
                  key: env
            - name: TOKEN_LIST
              valueFrom:
                configMapKeyRef:
                  name: tokeninfo
                  key: token_list
            - name: TOKEN_IMAGE_DIR
              valueFrom:
                configMapKeyRef:
                  name: tokeninfo
                  key: token_image_dir
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true