{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "tokeninfo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tokeninfo.name" . }}
    environment: {{ .Values.environment }}
    chart: {{ template "tokeninfo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ template "tokeninfo.fullname" . }}
              servicePort: {{ .Values.service.port }}
{{- end }}
