name: pull-request-deployment

on:
  pull_request:
    types: [labeled]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'deploy'
    steps:
    - name: get pull request ref
      id: get_pull_request_ref
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/:repository/pulls/:issue_id
        repository: ${{ github.repository }}
        issue_id: ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: create deployment
      id: create_deployment
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/:repository/deployments
        repository: ${{ github.repository }}
        ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}
        environment: testing
        auto_merge: false
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: set deployment status to in progress
      id: start_deployment
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/:repository/deployments/:deployment/statuses
        repository: ${{ github.repository }}
        ref: ${{ fromJson(steps.create_deployment.outputs.data).id }}
        environment: testing
        environment_url: https://${{ fromJson(steps.create_deployment.outputs.data).id }}.test.endpass.com
        log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        state: in_progress
        media_type: '{"previews": ["flash", "ant-man"]}'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: deployment logic
      run: |
        sleep 10
        exit $(( $RANDOM % 10 >= 5))

    - name: set deployment status to success
      id: successful_deployment
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/:repository/deployments/:deployment/statuses
        repository: ${{ github.repository }}
        ref: ${{ fromJson(steps.create_deployment.outputs.data).id }}
        environment: testing
        environment_url: https://${{ fromJson(steps.create_deployment.outputs.data).id }}.test.endpass.com
        log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        state: success
        media_type: '{"previews": ["ant-man"]}'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: set deployment status to failure
      id: failed_deployment
      uses: octokit/request-action@v2.x
      if: failure()
      with:
        route: POST /repos/:repository/deployments/:deployment/statuses
        repository: ${{ github.repository }}
        ref: ${{ fromJson(steps.create_deployment.outputs.data).id }}
        environment: testing
        environment_url: https://${{ fromJson(steps.create_deployment.outputs.data).id }}.test.endpass.com
        log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        state: failure
        media_type: '{"previews": ["ant-man"]}'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
