name: pull-request-review-undeployment

on:
  pull_request:
    types: [unlabeled,closed]

jobs:  
  undeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install multiwerf
      run: |
        # add ~/bin into path
        export PATH=$PATH:$HOME/bin
        echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
        # install multiwerf into ~/bin directory
        mkdir -p ~/bin
        cd ~/bin
        curl -L https://raw.githubusercontent.com/flant/multiwerf/master/get.sh | bash
        echo "::add-path::$HOME/bin"

    - name: Create kubeconfig
      run: |
        KUBECONFIG=$(mktemp -d)/config
        echo $BASE64_KUBECONFIG | base64 -d -w0 > $KUBECONFIG
        echo ::set-env name=KUBECONFIG::$KUBECONFIG
      env:
        BASE64_KUBECONFIG: ${{ secrets.BASE64_KUBECONFIG }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Undeploy from k8s
      id: undeploy-from-k8s
      env:
        WERF_STAGES_STORAGE: ${{ steps.login-ecr.outputs.registry }}/stages/tokeninfo
        WERF_IMAGES_REPO: ${{ steps.login-ecr.outputs.registry }}/review/tokeninfo
        WERF_HELM_RELEASE_STORAGE_NAMESPACE: werf-releases
        WERF_HELM_RELEASE_STORAGE_TYPE: secret
      run: |
        . $(multiwerf use 1.1 stable --as-file)
        werf dismiss --release tokeninfo-review --namespace review
  
    - name: Delete DNS record
      id: delete_dns_record
      env:
        RESOURCE_RECORD_NAME: ${{ github.event.pull_request.number }}-tokeninfo.review.endpass.com
        RESOURCE_RECORD_VALUE: ${{ secrets.RESOURCE_RECORD_VALUE }}
      run: |
        aws route53 change-resource-record-sets --hosted-zone-id ${{ secrets.HOSTEDZONE_ID }} \
        --change-batch '{ "Comment": "Testing creating a record set", "Changes": [ { "Action": "DELETE", "ResourceRecordSet": { "Name": "'"$RESOURCE_RECORD_NAME"'", "Type": "CNAME", "TTL": 120, "ResourceRecords": [ { "Value": "'"$RESOURCE_RECORD_VALUE"'" } ] } } ] }'
        
    - name: Mark environment as deactivated
      uses: bobheadxi/deployments@master
      with:
        step: deactivate-env
        token: ${{ secrets.GITHUB_TOKEN }}
        env: review
        desc: Deployment was pruned
