name: pull-request-undeployment

on:
  pull_request:
    types: [unlabeled,closed]

jobs:  
  undeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
  
    - name: Undeploy
      uses: gridwave/helm-deployer@master
      with:
        task: 'remove'
        release: tokeninfo
        namespace: review
        chart: app
        helm: helm3
        version: ${{ github.sha }} 
      env:
        KUBECONFIG_FILE: "${{ secrets.KUBECONFIG }}"
        
    - name: mark environment as deactivated
      uses: bobheadxi/deployments@master
      with:
        step: deactivate-env
        token: ${{ secrets.GITHUB_TOKEN }}
        env: review
        desc: Deployment was pruned
