name: pull-request-review-undeployment

on:
  pull_request:
    types: [unlabeled,closed]

jobs:  
  undeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
  
    - name: Undeploy
      uses: gridwave/helm-deployer@master
      with:
        task: 'remove'
        release: tokeninfo
        namespace: review
        chart: ./charts/tokeninfo
        version: ${{ github.sha }} 
      env:
        KUBECONFIG_FILE: "${{ secrets.KUBECONFIG }}"

    - name: Create DNS record
      id: create_dns_record
      env:
        RESOURCE_RECORD_NAME: ${{ github.event.pull_request.number }}-tokeninfo.review.endpass.com
        RESOURCE_RECORD_VALUE: ${{ secrets.RESOURCE_RECORD_VALUE }}
      run: |
        aws route53 change-resource-record-sets --hosted-zone-id ${{ secrets.HOSTEDZONE_ID }} \
        --change-batch '{ "Comment": "Testing creating a record set", "Changes": [ { "Action": "DELETE", "ResourceRecordSet": { "Name": "'"$RESOURCE_RECORD_NAME"'", "Type": "CNAME", "TTL": 120, "ResourceRecords": [ { "Value": "'"$RESOURCE_RECORD_VALUE"'" } ] } } ] }'
        
    - name: Mark environment as deactivated
      uses: bobheadxi/deployments@master
      with:
        step: deactivate-env
        token: ${{ secrets.GITHUB_TOKEN }}
        env: review
        desc: Deployment was pruned
