name: dockerfile lint
on:
  pull_request:
    branches:
      - master
      - release
    paths:
      - "docker/Dockerfile"

jobs:
  dockerfile_lint:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: dockerfile sweep for best practices
      uses: burdzwastaken/hadolint-action@master
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         HADOLINT_ACTION_DOCKERFILE_FOLDER: docker/
         HADOLINT_ACTION_COMMENT: false
